# Project information
site_name: GPT Engineer Docs
site_url: https://docs.gptengineer.app/
# SEO notice: https://docs.gptengineer.app/sitemap.xml
docs_dir: src
site_description: GPT Engineer app project documentation. Learn more about GPT Engineer, its features and get up to speed.

# Copyright
copyright: "&copy; 2023 - 2024 ❤️ Lovable"
# Navigation
nav:
  - "Introduction": index.md
  - "User guides":
      - "Getting started": getting-started.md
      - "Messaging limits": credits.md
      - "Free edits": free-credits.md

  - "Features":
      - "Features overview": features/index.md
      - "Deployment and sharing": features/deploy.md
      - "Using npm packages": features/npm-packages.md
      - "Tech stacks": features/techstacks.md
    #- features/import-project.md

  - "Integrations":
      - "Integrations overview": integrations/index.md
      - "GitHub integration": features/git-integration.md
      - "Supabase integration": integrations/supabase.md

  - "Tips and tricks":
      - "Working with images": tips-tricks/using-images.md
      - "Working with videos": tips-tricks/using-videos.md
      - "Using custom fonts": tips-tricks/custom-fonts.md
      - "Multiple users": tips-tricks/multiple-users.md
      - "Custom domains": tips-tricks/custom-domain.md
      - "Prompting tips and strategies": tips-tricks/prompting.md

# Configuration
theme:
  name: material
  locale: en
  logo: assets/gpt-engineer-2x-logo.png
  favicon: assets/favicon-32x32.png
  palette:
    # Light mode as default
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode (optional)
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - navigation.top
    - nagivation.tabs
    - toc.follow
    - content.code.copy
    - content.action.edit

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/solid/heart
      link: https://lovable.dev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Lovable_dev
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@lovable-labs
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rPw2rSFE2K
    - icon: fontawesome/brands/github
      link: https://github.com/gpt-engineer-org/gptengineer.app
  # removes "Made with Material for MkDocs", we should sponsor the project instead (as they suggest in their docs)
  generator: false

extra_css:
  - assets/css/styles.css

# Repository URL
repo_url: https://github.com/lovablelabs/docs
edit_uri: edit/main/src
